"""
Django settings for MyTwinAI project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR.parent / '.env')


def env_list(name: str) -> list[str]:
    """A comma separated environment variable, e.g. "a.com, b.com"."""
    return [item.strip() for item in os.getenv(name, '').split(',') if item.strip()]


# The defaults are the development ones, so nothing needs setting locally.
# Every one of them is overridden by an environment variable in production.

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'django_secret_key',
    'django-insecure-wo1wf6h_izxl6q-(0p7^h^3^6e4vt1ibp7!$2xx5t9fmgh8&4e',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('django_debug', 'true').lower() == 'true'

# Hugging Face terminates TLS in front of the app and forwards the real host,
# so the host header cannot be pinned to one name.
ALLOWED_HOSTS = env_list('django_allowed_hosts') or ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chat',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# The frontend is on a different domain to the API, so it has to be named here
# or the browser blocks every request. Set cors_allowed_origins to the Vercel
# URL in production, e.g. "https://mytwinai.vercel.app".
CORS_ALLOWED_ORIGINS = env_list('cors_allowed_origins') or [
    'http://localhost:5173',
]

# Vercel gives every deployment its own preview URL, which cannot be listed one
# by one. Set cors_allow_all to true only if you want those to work too.
CORS_ALLOW_ALL_ORIGINS = os.getenv('cors_allow_all', 'false').lower() == 'true'

ROOT_URLCONF = 'MyTwinAI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MyTwinAI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
